[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect API routes to Netlify Functions
[[redirects]]
  from = "/api/subgraph"
  to = "/.netlify/functions/api-subgraph"
  status = 200

[[redirects]]
  from = "/api/market/prices"
  to = "/.netlify/functions/api-market-prices"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https: blob:; object-src 'none'; base-uri 'self'; connect-src 'self' https: wss:; img-src 'self' data: blob: https:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; frame-ancestors 'none'; form-action 'self'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), microphone=(), payment=()"
